name: Bug Report
description: Create a report to help us improve
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        **Please verify your issue hasn't been reported before by searching the issue tracker.**
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: How do we reproduce this? Provide exact steps if possible.
    validations:
      required: true
  - type: input
    id: app-version
    attributes:
      label: App Version
      description: What version of Hikari are you using?
      placeholder: "e.g. 1.0.0"
    validations:
      required: true
  - type: input
    id: device
    attributes:
      label: Device and OS version
      description: E.g., Samsung Galaxy S23 Ultra, Android 13
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen instead?
  - type: textarea
    id: logs
    attributes:
      label: Crash logs
      description: If the app crashed, please provide a crash log here (via logcat or the internal crash logger).
